import {
  ALPHA_NUMERIC_REGEX,
  ALPHABETS_REGEX,
  ALPHABETS_WITH_HYPEN_AND_SPACE,
  ALPHABETS_WITH_SPACE_REGEX,
  ALPHANUMERIC_SPECIAL_CHAR_REGEX,
  EMAIL_REGEX,
  FLOAT_REGEX,
  LOOSE_ALPHA_NUMERIC_REGEX,
  NAME_REGEX,
  NUMBER_REGEX,
  URL_REGEX,
} from "./regex";

export const VALIDATORS = {
    URL: 'URL',
    EMAIL: 'EMAIL',
    NAME: 'NAME',
    ALPHANUMERIC_SPECIAL_CHAR: 'ALPHANUMERIC_SPECIAL_CHAR',
    ALPHABETS_WITH_HYPEN_AND_SPACE: 'ALPHABETS_WITH_HYPEN_AND_SPACE',
    ALPHA_NUMERIC: 'ALPHA_NUMERIC',
    ALPHABETS: 'ALPHABETS',
    ALPHABETS_WITH_SPACE: 'ALPHABETS_WITH_SPACE',
    LOOSE_ALPHA_NUMERIC: 'LOOSE_ALPHA_NUMERIC',
    NUMBER: 'NUMBER',
    FLOAT: 'FLOAT',
};

export const ValidateRegex = {
    [VALIDATORS.URL]: URL_REGEX,
    [VALIDATORS.EMAIL]: EMAIL_REGEX,
    [VALIDATORS.NAME]: NAME_REGEX,
    [VALIDATORS.ALPHANUMERIC_SPECIAL_CHAR]: ALPHANUMERIC_SPECIAL_CHAR_REGEX,
    [VALIDATORS.ALPHABETS_WITH_HYPEN_AND_SPACE]: ALPHABETS_WITH_HYPEN_AND_SPACE,
    [VALIDATORS.ALPHA_NUMERIC]: ALPHA_NUMERIC_REGEX,
    [VALIDATORS.ALPHABETS]: ALPHABETS_REGEX,
    [VALIDATORS.ALPHABETS_WITH_SPACE]: ALPHABETS_WITH_SPACE_REGEX,
    [VALIDATORS.LOOSE_ALPHA_NUMERIC]: LOOSE_ALPHA_NUMERIC_REGEX,
    [VALIDATORS.NUMBER]: NUMBER_REGEX,
    [VALIDATORS.FLOAT]: FLOAT_REGEX,
};